latex input: mmd-article-header
Title: Leitfaden der Interview zum Thema File Management Systeme
Author: Marco Brochert, Anastasia Kazakova, Jens Rauch
Date: 10. Mai 2012
Base Header Level: 2
latex mode: memoir
latex input: mmd-article-begin-doc
latex footer: mmd-memoir-footer


PAGEBREAK

TESt

# Interview 1 #

> - _Notieren:_
	- **Geschlecht**
		- Männlich
	- **Alter**
		- 25
	- **Beruf/Beschäftigung**
		- Student/Informatik
	- **PC-Erfahrung (Schätzung von 1 bis 5 (1 ist der schlechteste, 5 - der beste Wert)**
		- 5 

1. **Zeigen Sie mir bitte, wie Sie Dateien, die Sie erstellen oder abspeichern, auf Ihrer Festplatte organisieren.**

	- Programm -> speichern unter
	- Es gib ein Order od. Unterordner. Oder es wird ein Ordner eingelegt
	- Modulen-Order sind Analog zu den Projekten
	-Hierarchie: Studium - Semesterordner (Kürzel) - Modulkürzel - Projekte/VL/Tutorium evtl. Vorträge von den Anderen

> - _Notieren:_
	- **OS**
		- Fedora/Linux
	- **File Manager (Explorer, Nautilus ...)**
		- Nautilus
	- **evtl. Erweiterungen (falls es die Erweiterungen, für die Verwaltung von Musik- od. Bilddateien gibt, sich zeigen lassen, fragen wie funktioniert, ob und womit man (un-)zufrieden ist)**
		- Keine Musik, da es keine sinnvolle Strategie/Möglichkeit gibt, sie zu verwalten
		- Bilder
			- Shotwell
			- Automatischer Inport
			- Hierarchie: Jahr-Monat-Tag
		- Tagging ist vorhanden, wird aber nicht genutzt

2. **Wie gehen Sie vor, wenn Sie eine Datei suchen, deren Ablageort Sie nicht mehr wissen?**

	- Kommt nicht vor
	- Wenn die Datei nicht aufzufinden ist, dann wird sie neu geladen. Ansonsten: was weg ist, ist weg
	- Randfall 2: Ich hab grobe Vorstellung
		- Suche von Nautilus
		- reine Faulheit: Keine Lust zu kicken
	- Inkrementelle Suche

3. **Wie könnten Sie gesuchte Dateien schneller auffinden?**

	- Wenn die Suche schnell wäre, dann würde ich es eventuell benutzen
	- Visionär: 
		- Sachen sind entweder auf der Platte oder im Backup
		- Falsch einsortiert
			- Rumsuchen, rumbrowsen, Nachbarordner
			- Problem: Aufwandig, Nicht aussagekräftige Datei-Namen
			- Keine globalle Suche, höchstens 2 Ebene nach oben

4. **Was hindert Sie daran Dateien schneller aufzufinden?**

	- Dateinamen
	- Performance von der Suche
	- Performance der Vorschau

5. **Was mich hindert Dateien schnell einzusortieren:**

	- Hierarchieproblem: Jeder Eintrag ein Begriff, jeder Begriff ist eine Definition
		- Es gibt immer wieder Grenzfälle in denen die Hierarchien nicht funktioneieren
		- Mulltiple Paradigmen:
			- Bilder gehören in ein Ordner. Was ist mit den Screenshots oder mit Graphiken für Projekte?
		- Was ist mit den Projektpartner? Alle haben unterschiedliche Vorstellungen
	- Faul für Shortcuts

PAGEBREAK


# Interview 2 #


> - _Notieren:_
	- **Geschlecht**
		- Weiblich
	- **Alter**
		- 25
	- **Beruf/Beschäftigung**
		- Psychologin/Reha-Klinik
	- **PC-Erfahrung (Schätzung von 1 bis 5 (1 ist der schlechteste, 5 - der beste Wert)**
		- 3 

1. **Zeigen Sie mir bitte, wie Sie Dateien, die Sie erstellen oder abspeichern, auf Ihrer Festplatte organisieren.**
	
	- entsprechend der Vorgabe von Windows in "Eigene Dateien" 
	- nach Dateityp organisiert: Bilder, Dokumente, Videos
	- thematisch nach Inhalt
	

> - _Notieren:_
	- **OS**
		- Windows 7
	- **File Manager (Explorer, Nautilus ...)**
		- Explorer
	- **evtl. Erweiterungen (falls es die Erweiterungen, für die Verwaltung von Musik- od. Bilddateien gibt, sich zeigen lassen, fragen wie funktioniert, ob und womit man (un-)zufrieden ist)**
		- Keine Erweiterungen

2. **Wie gehen Sie vor, wenn Sie eine Datei suchen, deren Ablageort Sie nicht mehr wissen?**

	- Ordner durchklicken, in denen sich die Datei befinden könnte
	- Suchfunktion. 
	- Umstellung auf Windows 7 --> Keine Suchfunktion gefunden
	- Kommt aber sehr selten vor, da alles an seinem Platz ist.

3. **Wie könnten Sie gesuchte Dateien schneller auffinden?**

	- Sorgfältiger darauf achten, dass alles sortiert ist

4. **Was hindert Sie daran Dateien schneller aufzufinden?**

	- Dateien werden manchmal versehentlich falsch abgelegt
	
PAGEBREAK

# Interview 3 #


> - _Notieren:_
	- **Geschlecht**
		- Männlich
	- **Alter**
		- 25
	- **Beruf/Beschäftigung**
		- Student/BWL
	- **PC-Erfahrung (Schätzung von 1 bis 5 (1 ist der schlechteste, 5 - der beste Wert)**
		- 3 

1. **Zeigen Sie mir bitte, wie Sie Dateien, die Sie erstellen oder abspeichern, auf Ihrer Festplatte organisieren.**

	- Dateien werden nicht organisiert 
	- Ablageort: Desktop oder Eigene Dateien	

> - _Notieren:_
	- **OS**
		- Windows Vista
	- **File Manager (Explorer, Nautilus ...)**
		- Explorer
	- **evtl. Erweiterungen (falls es die Erweiterungen, für die Verwaltung von Musik- od. Bilddateien gibt, sich zeigen lassen, fragen wie funktioniert, ob und womit man (un-)zufrieden ist)**
		- Keine Erweiterungen

2. **Wie gehen Sie vor, wenn Sie eine Datei suchen, deren Ablageort Sie nicht mehr wissen?**

	- Trifft aber nur auf selbst erstellte Dateien zu
		- Auf Desktop und in Eigene Dateien schauen
		- Suchfunktion. 
	- Extern erstellte Dokumente
		- ausschließlich online gesucht bzw. abgerufen, auch wenn sie lokal verfügbar wären.

3. **Wie könnten Sie gesuchte Dateien schneller auffinden?**

	- Nach neusten Dateien suchen:
		- Da Dateien nie über einen längeren Zeitraum hin benötigt werden

4. **Was hindert Sie daran Dateien schneller aufzufinden?**

PAGEBREAK

# Interview 4 #

> - _Notieren:_
	- **Geschlecht**
		männlich
	- **Alter**
		21
	- **Beruf/Beschäftigung**
		Student
	- **PC-Erfahrung (Schätzung von 1 bis 5 (1 ist der schlechteste, 5 - der beste Wert)** 
		3

**1. Beschreiben Sie mir bitte, wie Sie Dateien, die Sie erstellen oder abspeichern, auf Ihrer Festplatte organisieren.**
	- Patitionen:
		- C: Windows und temporäre Dateien. Kann ohne weiteren Datenverlust formatiert werden; Dropbox-Ordner(für unwiederbringliche und wirklich wichtige Sachen)
		- D: Multimedia mit wenigen Schreib-/Lesevorgängen und -Datenrate). Darauf Ordner für Musik (sortiert nach Alben, Hörspielen, ...), Fotos (eigene Aufnahmen [Ordnernamen ist Importierdatum], andere), Programme("Programmdateien", keine "Arbeitsdateien")
		- E: Spiele; Dateien die mit hohen Schreib-/Lesevorgängen oder/und -Datenraten und häufig ediert werden; nur weniger wichtige und wiederbringbare Dateien
		- U: Ubuntu. -Um windows zu formatieren und anderen Schabernack :D
		
	
> - Notieren:
	- **OS**
		Windows 7 (Ubuntu 11.10)
	- **File Manager (Explorer, Nautilus ...)**
		- Windows Explorer
		- Sortierung für Musikdateien übernimmt Foobar2000, Sortierung für Fotos Picasa
	- **evtl. Erweiterungen (falls es die Erweiterungen, für die Verwaltung von Musik- od. Bilddateien gibt, beschreiben Sie kurz wie sie funktioniert, ob und womit man (un-)zufrieden ist)**
		- Keine selbstinstallierten Erweiterungen. bin sehr zufrieden
		
2. **Wie gehen Sie vor, wenn Sie eine Datei suchen, deren Ablageort Sie nicht mehr wissen?**
	- Windowssuche (auch, wenn man seine kompletten Festplatten nach "typ:Bild" durchsucht); 
	- erkennen, dass man auch ohne die Datei leben kann(weil sie nicht im Dropbox-Ornder war).
3. **Wie könnten Sie gesuchte Dateien schneller auffinden?**
	- Tags
	- Spezielle Suchsoftware
	- Schnellere Festplatten (das annehmlichste)
4. **Was hindert Sie daran Dateien schneller aufzufinden?**
	- Das Problem besteht nicht wirklich





