latex input: mmd-beamer-IntSysTheme-header
Title: FileNetwork: Prototyp
Author: Anastasia Kazakova, Bengt Lüers
Date: 21. Juni 2012
latex mode: beamer
LaTeX XSLT: beamer
Theme: keynote-IntSysTheme
latex input: mmd-beamer-begin-IntSysTheme-doc
latex footer: mmd-beamer-IntSysTheme-footer


# #

## Anmerkungen

### Pidoco

-   wenige grundlegende Elemente => eigene Grafiken
-   kein Drag&Drop => Point & Clicks
-   kein Hovern => :(
-   keine Animation => :(

### Lösung

- Pfeile mit Links
- Button zum Wecheln zwischen Ansichten
- Suche nach einer besseren Lösung mit Pidoco


## Demo

### Demo

**Demo**


### Danke!

**Fragen? Anmerkungen?**
