latex input: mmd-beamer-IntSysTheme-header
Title: FileNetwork: Konzept zur Verbesserung des Prototypen
Author: Anastasia Kazakova, Bengt Lüers
Date: 11. Juli 2012
latex mode: beamer
LaTeX XSLT: beamer
Theme: keynote-IntSysTheme
latex input: mmd-natbib-plain
biblio style: chicago
latex input: mmd-beamer-begin-IntSysTheme-doc
latex footer: mmd-beamer-IntSysTheme-footer

# #

## Verbesserungskonzepte

### Download-Szenario

**Analyse**

-   Idee bewährt, Ausführung verbesserungsbedürftig

**Ansatz**

-   Visualisierung muss deutlicher als Download-Link zu erkennen sein

**Ideen**

-   Download-Button
-   Speichern-Symbol
-   Shelf beibehalten

### Losbrechmoment

**Analyse**

-   anfängliche Unsicherheit über Interaktionsarten
-   könnte abschrecken => wichtig für Produkt

**Ansatz**

-   richtige Aktion muss provoziert werden

**Ideen**

-   einmaliges Tutorial
-   textueller Hinweis
-   Hervorheben beim Hovern

### Datei aus Kreis entfernen

**Analyse**

-   mehrstufige Aktion nötig
-   orthogonal zum Hinzufügen

**Ansatz**

-   richtige Aktion muss klar werden

**Ideen**

-   Kreise hervorheben, wenn anklickbar
-   einmaliges Tutorial
-   Hervorheben beim Hovern

### In Verbindungsansicht wechseln

**Analyse**

-   Zweite Sicht auf System wurde nicht verstanden

**Ansatz**

-   Zusammenhang zwischen Sichten vermitteln

**Ideen**

-   Aufteilung analog halten
-   Animation
-   Farben von Kreisen für Verbindungen übernehmen

### Vorschläge

**Analyse**

-   Vorschläge nicht nachvollziehbar

**Ansatz**

-   Vorschläge erklären

**Ideen**

-   ToolTip
-   Statusleiste

### Ausblick

-   Maschinelles Lernen kann weiter vorausgesetzt werden
-   Interaktionsweisen, die Pidoco nicht erlaubt hat, erwägen
    -   logischen Aufbau beibehalten
    -   intuitivere Interaktion durch Drag&Drag
-   Skalierbarkeit testen
    -   Fake-Backend

        Viele Dateien, viele Verbindungen
        vielleicht im Frontend
    -   Fake-Frontend

        spannungsoriente Visualisierung
        älter => kleiner

### Danke

**Fragen? Anmerkungen?**
