all:
	# 1_BRK_Konzept_zur_Requirements_Analyse
	multimarkdown -t latex ./1_BRK_Konzept_zur_Requirements_Analyse.mmd > 1_BRK_Konzept_zur_Requirements_Analyse.tex
	pdflatex 1_BRK_Konzept_zur_Requirements_Analyse.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 1_BRK_Konzept_zur_Requirements_Analyse.tex
	#evince 1_BRK_Konzept_zur_Requirements_Analyse.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex

	# 2_BRK_Ergebnisse_der_Requirements_Analyse
	multimarkdown -t latex ./2_BRK_Ergebnisse_der_Requirements_Analyse.mmd > 2_BRK_Ergebnisse_der_Requirements_Analyse.tex
	pdflatex 2_BRK_Ergebnisse_der_Requirements_Analyse.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 2_BRK_Ergebnisse_der_Requirements_Analyse.tex
	#evince 2_BRK_Ergebnisse_der_Requirements_Analyse.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex

	# 3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns
	multimarkdown -t latex ./3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns.mmd > 3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns.tex
	pdflatex 3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns.tex
	#evince 3_BRK_Methodisches_Vorgehen_zur_Entwicklung_des_Strukturdesigns.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex

	# 4_BRK_Strukturdesign
	multimarkdown -t latex ./4_BRK_Strukturdesign.mmd > 4_BRK_Strukturdesign.tex
	pdflatex 4_BRK_Strukturdesign.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 4_BRK_Strukturdesign.tex
	#evince 4_BRK_Strukturdesign.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex


	# 5_BRK_Reflection_Guidelines
	multimarkdown -t latex ./5_BRK_Reflection_Guidelines.mmd > 5_BRK_Reflection_Guidelines.tex
	pdflatex 5_BRK_Reflection_Guidelines.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 5_BRK_Reflection_Guidelines.tex
	#evince 5_BRK_Reflection_Guidelines.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex


	# 6_BRK_Prototyp
	multimarkdown -t latex ./6_BRK_Prototyp.mmd > 6_BRK_Prototyp.tex
	pdflatex 6_BRK_Prototyp.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 6_BRK_Prototyp.tex
	#evince 6_BRK_Prototyp.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex


	# 7_BRK_Prototyp_Studie
	multimarkdown -t latex ./7_BRK_Prototyp_Studie.mmd > 7_BRK_Prototyp_Studie.tex
	pdflatex 7_BRK_Prototyp_Studie.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 7_BRK_Prototyp_Studie.tex
	#evince 7_BRK_Prototyp_Studie.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex


	# 8_BRK_Userstudie_Ergebnisse
	multimarkdown -t latex ./8_BRK_Userstudie_Ergebnisse.mmd > 8_BRK_Userstudie_Ergebnisse.tex
	pdflatex 8_BRK_Userstudie_Ergebnisse.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 8_BRK_Userstudie_Ergebnisse.tex
	#evince 8_BRK_Userstudie_Ergebnisse.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex


	# 9_BRK_Konzept_zur_Verbesserung_des_Prototypen
	multimarkdown -t latex ./9_BRK_Konzept_zur_Verbesserung_des_Prototypen.mmd > 9_BRK_Konzept_zur_Verbesserung_des_Prototypen.tex
	pdflatex 9_BRK_Konzept_zur_Verbesserung_des_Prototypen.tex
	#bibtex Vortragsvorlage
	#pdflatex Vortragsvorlage.tex
	pdflatex 9_BRK_Konzept_zur_Verbesserung_des_Prototypen.tex
	#evince 8_BRK_Userstudie_Ergebnisse.pdf
	rm *.aux *.log *.out *.nav *.snm  *.toc *.tex
