latex input: mmd-ba-notes-header
Title: Leitfaden für User Study
Author: Anastasia Kazakova, Bengt Lüers
Base Header Level: 2
latex mode: memoir
bibtex: Literaturliste
biblio style: chicago
latex input: mmd-ba-notes-begin-doc
latex footer: mmd-ba-notes-footer


PAGEBREAK

# Leitfaden #

## Definiere Aufgaben ##

Das System ist neu, aber nicht leer. Unsere alte Dateien sind zwar da, aber ausgeblendet. Im Momemt arbeiten wir mit dem FileNetwork und händeln unsere Tätigkeiten damit. Dadurch lehren wir es. Später wenn wir meinen, dass FileNetwork bereit ist, lassen wir es auf die alte Dateien los und lassen sie einsortieren. 

Wir fangen an zu arbeiten. Wir wollen einen Vortrag vorbereiten. Alle benötigte Informationen bekommen wir entweder aus dem Netz (Papers zum Thema, andere Vorträge, etc.) oder aus dem gemeisamen Repository (z.B. Experimet-Rohdaten), das via Internet zu erreichen ist.

**Scenario 1**
Wir laden die benötigte Unterlagen runter (

- (Übersicht) Browser starten
- Browser ist gestartet, richtige Seite ist gefunden
- Wir laden die Dateien nach einander runter
- (Übersicht) Die geladenen Datein sind in der Mitte

**Scenario 2**
Wir hollen uns Experiment-Rohdaten.





### Aufgaben ###






PAGEBREAK

