latex input: mmd-beamer-IntSysTheme-header
Title: FileNetwork: Konzept zur Requirements-Analyse
Author: Anastasia Kazakova, Jens Rauch, Marco Brochert
Date: 5. Mai 2012
latex mode: beamer
LaTeX XSLT: beamer
Theme: keynote-IntSysTheme
latex input: mmd-natbib-plain
latex input: mmd-beamer-begin-IntSysTheme-doc
latex footer: mmd-beamer-IntSysTheme-footer

# #

## State of the Art

### angebotene Möglichkeiten

**Einsortieren**

-   manuell in Ordner
-   manuell taggen

**Suchen**

-   in Ordnern
-   globale Suche
-   nach Tags

### Zusätzliche Anwendungen

-   Unterstützung durch bessere und bequemere GUI

**Einsortieren**

-   Taggen beim Herunterladen oder Erstellen der Dateien

**Suchen**

-   nach Tags

###  Aus der Literatur

**Suchen**[^1]

-   nach Metadaten (z.B. Google Desktop)
-   nach Inhalt (z.B. Google Desktop)

[^1]: S. Dekeyser, R. Watson, L. Motrøen _A Model, Schema, and Interface for Metadata File Systems_.

###  Aus der Literatur

**VennFS2-Tool**[^2]

-   eine Datei gehört zu mehreren Kategorien
-   Vorschläge der Anordnung
-   Visualisierung durch Venn-Diagramme

[^2]: R. De Chiara, U. Erra, V. Scarano _A Visual Adaptive Interface to File Systems_.

### Mögliche Konzepte

-   automatische Assoziation von Dateien auf Basis der Gebrauchshistorie
-   automatische/manuelle Zuordnung von (optional hierarchisch geordneten) Tags
-   interaktive Visualisierung des FileNetworks über Filter
-   interaktives Navigieren durch Verfolgen von Assoziationen zwischen Dateien/Tags

## Anforderungserhebung

### Zielgruppe und Methode
**Zielgruppe**

-   regelmäßige PC-Nutzer
-   ausschließen von Kindern und Menschen über 60 Jahren

**Methode**

-   Qualitatives Leitfadeninterview
-   Beobachtung

### Leitfaden


1.  Zeigen Sie mir bitte, wie Sie Dateien, die Sie erstellen oder abspeichern,
    auf Ihrer Festplatte organisieren.
2.  Wie gehen Sie vor, wenn Sie eine Datei suchen, deren Ablageort Sie nicht mehr wissen?
3.  Wie könnten Sie gesuchte Dateien schneller auffinden?
4.  Was hindert Sie daran Dateien schneller aufzufinden?

	        
### Leitfaden 

Notieren:
- Betriebssystem
- Dateimanager (Windows Explorer, Nautilus ...)
- eventuell Erweiterungen für Bild- und Musikverwaltung
	- Zeigen lassen
	- Funktion erklären lassen
	- Vorzüge und Mängel erläutern lassen      


### Danke!

**Fragen? Anmerkungen?**

