latex input: mmd-beamer-IntSysTheme-header
Title: FileNetwork: Methodisches Vorgehen zur Entwicklung des Strukturdesigns
Author: Anastasia Kazakova, Bengt Lüers
Date: 24. Mai 2012
latex mode: beamer
LaTeX XSLT: beamer
Theme: keynote-IntSysTheme
latex input: mmd-natbib-plain
latex input: mmd-beamer-begin-IntSysTheme-doc
latex footer: mmd-beamer-IntSysTheme-footer


# #

## Getting Started

### Anwender

-   Alter: 18 - 55 Jahre
-   Nutzertyp: Student, Büromitarbeiter oder aktiver PC-Nutzer
-   Gerätetyp: Desktop/Laptop
-   Verhalten: Prosument

### Ziele

-   **Anwendungsziele**
	-   (Datei)Management

-   **Anwenderziele**
	-   Lösung von spezifischen Probleme
		-   Einsortieren von Dateien
		-   Suchen/Finden von Dateien

### Inhalt

-   **Dateien**
-   **Tags**
	-   manuell eingegeben
	-   vollständige Liste aller Tags
	-   durch das System vorgeschlagene Tags  
	    (z.B. Schlüsselworte aus dem Dateiinhalt)

-   **Verbindungen zwischen Dateien**
	-   durch System hergestellt
	-   durch Anwender angegeben

## Strukturdesign

### Ebenen der Anwendung

-   **Dateien Einsortieren**
	-   neue
	-   vorhandene

-   **Nach Dateien suchen**
-   **Graphische Visualisierung des Netzwerks**
 
### Weiteres Vorgehen

-   **Ebenen der Anwendung**
	-   Inhalte weiter eingrenzen

-   **GUI-Elemente ausarbeiten**
	-   weg von gewohnten Fenstern
	-   Graphische Visualisierung für alle Ebenen

### Danke!


**Fragen? Anmerkungen?**

