latex input: mmd-beamer-IntSysTheme-header
Title: FileNetwork: Reflexion der Usability Guidelines
Author: Anastasia Kazakova, Bengt Lüers
Date: 14. Juni 2012
latex mode: beamer
LaTeX XSLT: beamer
Theme: keynote-IntSysTheme
latex input: mmd-natbib-plain
biblio style: chicago
latex input: mmd-beamer-begin-IntSysTheme-doc
latex footer: mmd-beamer-IntSysTheme-footer


#  #

## Goldene Regeln

### Golden Rule 1: Consistency

-   Dateien durch Symbole (Dateityp) und Name
-   Kreise zum Zusammenfassen
-   Verbindungen zwischen Dateien

- Pie-Menues (?)

### Beispiel

![](01.png)

### Golden Rule 3: Informative Feedback

-   Hervorheben von erstellten Verbindungen
-   Hervorheben von eingeordneten Kreisen
-   Permanentes Anzeigen der Dateien

### Beispiel

![](02.png)

### Golden Rule 5: Prevent Errors

-   Durch das Feedback 
	-   nachvollziehbare Aktionen
-   Snappen
	-   Halten in der ungefähren Richtung reicht

### Golden Rule 7: User Control

-   in der Lern-/Anfangsphase, ansonsten

-   brechen wir, denn:
	-   Maschinelles Lernen
	-   Bereitschaft sich helfen zu lassen

## Guidelines

### Organizing the Display

-   Aktuelle Dateien in der Mitte

### Beispiel

![](03.png)

### Getting the User's Attention

-   Verbindungen
	-   keine Intensität => nicht vorhanden
	-   Intensität 1 => Vorhanden
	-   Intensität 2 => Hervorgehoben

-   Dateien
	-   groß => aktuell
	-   klein => veraltet

-   Kreise
	-   Farbe für Identifikation
	-   Mischfarben für Überlappungen

### Beispiel

![](04.png)

### Beispiel

![](05.png)

## Standards

### Conformity with User's Expectations

-   Gezogene Datei landet ungefähr da, wo sie losgelassen wurde

### Beispiel
![](06.png)

### Beispiel

![](07.png)

### Error Tolerance

-   Snapping
-   Instant Feedback

### Suitability for Individualization

-   Farbauswahl durch Nutzer

### Danke! ###

**Fragen? Anmerkungen?**

