zu Strukturdesign

Zugang von Visualisierung aus
von herkömmmlichen Datemanagern lösen

Brainstoming

-   Dateien
-   Kanten,
-   Einkreisen

UI Puzzle

-   Kanten und 

Aufgaben:

-   1. Dateien + Stifte
-   2. Dateien + Stifte + Tags, Verbindungen, Dateien

Ziel:

-   Ideen sammeln
    -   Wichtiges/Aktuelles in die Mitte
    -   Unwichtiges/veratletes and den Rand
-   Bewusstsein für beseondere Bedürfnisse wecken
    -   Aufräumknopf
    -   dynamische Anpassung des Dateisystems an Nutzung

Archiv:

-   Probandin 1 
    -   mitte - aktuell/wichtig,
    -   ecken - alt/unwichtig,
    -   Schublade archiv
-   Probandin 2
    -   Rot + Oben => Archiv
    -   Gelb + Mitte => auf Abruf
    -   Grün + unten => Aktuell
-   Proband 3
    -   oben/mitte/unten <-> neu/mittel/alt
    -   offen => eingestrichelt, geschlossen => Rahmen, Archiv doppelt geschlossen
    -   nach Datum sortierte Haufen mit aktuellstem Element zum direkten Zugriff

Farben

-   Zur zuordnung farbig umranden
-   Muster in Umrandung für Aktualität
-   Farbmischung für Zwischendateien
-   Farbmuster für Zwischendateien
-   Farbige Kreisbogenabschnitte für Zugehörigkeit
    
Konzentrische Kreise für neu/mittel/alt werden als valide wahrgenommen

Wir arbeiten mit

-   Kreise
-   Farben
-   Entfernung zur Bildschirmmitte als Aktualitätsindikator

Emotionales Feedback

-   Teilnehmer 1:
    -   Farbe hat hohen Symbolwert (BA => rot)
    -   Verwahrlosung vermeiden
        -   durch Gestaltungsraum
        -   durch maschinelle Unterstützung
    -   Drang nach Zukunft
-   Teilnehmerin 2:
    -   Hohes Engagement
    -   Farben persönlich zu geordnet (BA => grün)
    -   kann sich an Dateien erinnern
    -   persönlicher Ausdruck Strukturierung
    -   Liebe zum Detail
-   Terilnehmer 3:
    -   Ist auf Dateimanager angewiesen
    -   hohe Bereitschaft sich vom System helfen zu lassen
    -   großes Problembewusstsein
    -   Aussicht auf bessere Welt
